name: dart_server_groups
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

dependencies:
  excel: ^4.0.6
  get_it: ^8.0.3
  postgres: ^3.5.6
  shelf: ^1.4.0
  shelf_multipart: ^2.0.1
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
